### ISSUE TITLE
Magma A #8 Incorrect placement for tile

### ISSUE THREAD

**Issue by bm0081** [while-loop/runelite-plugins#70] opened 2024-09-28 00:37 UTC
![image](https://github.com/user-attachments/assets/9804c757-29cd-4d05-a557-fc75ddab63a5)
Current image for Magma A #8 indicates that the player should stand on the left pillar's safespot for this phase - however, this results in them getting venomed during this phase. This image should instead indicate to move to the right pillar's safespot for this phase, with the same placement as Magma A #9.
![image](https://github.com/user-attachments/assets/e5a80a83-2cf6-41a6-ba9d-3329fc8ab82a)

**Comment by Rowan-Mulder** [comment] 2024-10-29 19:30
Similarly, I noticed SERP #3 isn't correct.
![image](https://github.com/user-attachments/assets/322c8fda-bbf1-4818-94f4-da8e2fcde4f5)

**Comment by raiyni** [comment] 2024-10-29 19:36
Original issue is really a duplicate of https://github.com/while-loop/runelite-plugins/issues/25

**Closed by raiyni** 2024-10-29 19:36 UTC
